"""Favicon drawings (R6, rebuilt after QA). Two kinds, one geometry.

1. VECTOR (favicon.svg, mask-icon.svg): the master kite itself, drawn with true 36/54-degree edges and NO
   shape-rendering hint, so every DPR (1, 1.25, 1.5, 1.75, 2, 3) rasterises it natively and mirror-symmetrically.
   (The old favicon.svg was the 16-grid pixel map with crispEdges: at fractional DPRs each edge snapped
   independently, so the glyph went lopsided and the core became a plus; at 2x retina tabs only ever showed the
   doubled 16 drawing.)  Tile 32 x 32 units, rx 6. Kite: master construction (geom.kite) with height 28 units,
   apex at y = 2; ring 3.6u (15% of the width); 2-unit spine gaps on x = 15..17 (whole pixels at 32 and 64 px);
   solid Saffron panel at 0.38 of the kite (the Small master's 0.34, opened slightly for 16-24 px) with its side
   vertices on the master panel axis y = 10.5u, i.e. 1.78u below the shoulder. No tail (R1).

2. PIXEL FRAMES (favicon-16/32/48.png and favicon.ico): hand-pixelled, no anti-aliasing inside the tile.
   32 and 48 are the vector drawing thresholded at 50% coverage, then hand-cleaned (32: core row 12 widened to
   the 4:3 rhythm 2-4-8-10). They keep the master angles: upper edges step 1,2,1,2,1,1,2,1 (11:8, 36 deg),
   lower edges 1,1,1,0 (3:4, 54 deg); shoulder at 34% of the ink height; ring 4-5 px perpendicular (15%);
   kite-shaped core 38% of the width, widest row just below the shoulder; 2px spine gaps on whole pixels
   (x 15-16 at 32, x 23-24 at 48).
   16 is drawn by hand (thresholding gives a cross-shaped core): 36/54-degree steps (upper 1,2,1,1; lower
   1,0,1,1,1,0,1), 3px upper / 2px lower ring (equal perpendicular weight), a 2-4-6-4-2 Saffron diamond whose
   widest row sits on the shoulder, a solid tip below the hollow as in the master, and no spine gap (R6: gaps
   only from a 32px tile up). The 5-row diamond needs the rows, so the 16 shoulder sits at 42% of the height.

Map keys: L ring (Lapis-200), S core (Saffron-400), N tile (Night). '#' = L, 'o' = S, '.' = N.
"""
import math
import geom as G

MAP16 = """
................
................
.......##.......
......####......
....###..###....
...###.oo.###...
..###.oooo.###..
..##.oooooo.##..
...##.oooo.##...
...##..oo..##...
....##....##....
.....##..##.....
......####......
.......##.......
................
................
"""

MAP32 = """
................................
................................
................................
..............#..#..............
.............##..##.............
...........####..####...........
..........#####..#####..........
........#######..#######........
.......#######....#######.......
......######........######......
....#######....oo....#######....
...#######....oooo....#######...
...######...oooooooo...######...
....#####..oooooooooo..#####....
.....#####..oooooooo..#####.....
.....#####..oooooooo..#####.....
......#####..oooooo..#####......
.......#####..oooo..#####.......
........#####.oooo.#####........
........#####..oo..#####........
.........#####....#####.........
..........#####..#####..........
...........####..####...........
...........####..####...........
............###..###............
.............##..##.............
.............##..##.............
..............#..#..............
................................
................................
................................
................................
"""

MAP48 = """
................................................
................................................
................................................
................................................
................................................
.....................##..##.....................
...................####..####...................
..................#####..#####..................
................#######..#######................
...............########..########...............
..............#########..#########..............
............##########....##########............
...........##########......##########...........
..........##########........##########..........
........##########............##########........
.......##########......oo......##########.......
.....###########......oooo......###########.....
....##########.......oooooo.......##########....
.....########......oooooooooo......########.....
.....########.....oooooooooooo.....########.....
......########...oooooooooooooo...########......
.......#######...oooooooooooooo...#######.......
........#######...oooooooooooo...#######........
........########...oooooooooo...########........
.........########..oooooooooo..########.........
..........#######...oooooooo...#######..........
...........#######...oooooo...#######...........
...........########...oooo...########...........
............#######...oooo...#######............
.............#######...oo...#######.............
.............########......########.............
..............########....########..............
...............#######....#######...............
................#######..#######................
................#######..#######................
.................######..######.................
..................#####..#####..................
...................####..####...................
...................####..####...................
....................###..###....................
.....................##..##.....................
.....................##..##.....................
................................................
................................................
................................................
................................................
................................................
................................................
"""

_KEY = {'.': 'N', '#': 'L', 'o': 'S'}


def grid(n):
    txt = {16: MAP16, 32: MAP32, 48: MAP48}[n]
    rows = txt.strip('\n').split('\n')
    px = [[_KEY[ch] for ch in r] for r in rows]
    assert len(px) == n and all(len(r) == n for r in px), n
    assert all(r[c] == r[n - 1 - c] for r in px for c in range(n)), f'{n}: not mirror-symmetric'
    return px


# ---------------------------------------------------------------- vector drawing (32-unit tile)
TILE = 32
TILE_RX = 6
KITE_H = 28.0       # units, apex to bottom vertex
KITE_TOP = 2.0
GAP = 2.0           # units: spine gap, x 15..17
PANEL = 0.38
PANEL_Y = G.PANEL_Y


def vector():
    """Ring halves and core as polygons in the 32-unit tile, coordinates rounded to 0.1 and mirrored exactly."""
    u = KITE_H / G.BODY_H
    s = G.STROKE; g = GAP / u / 2
    hT, hB, H = G.H_TOP, G.H_BOT, G.BODY_H
    iT = s / math.sin(math.radians(54)); iB = H - s / math.sin(math.radians(36))
    n1 = (math.sin(math.radians(36)), math.cos(math.radians(36))); n2 = (math.cos(math.radians(36)), -math.sin(math.radians(36)))
    iL = (s * (n1[0] + n2[0]), hT + s * (n1[1] + n2[1]))
    xc = 12 - g
    left = [(xc, hT * (12 - xc) / 12), (0, hT), (xc, hT + hB * xc / 12), (xc, iB - hB * (12 - xc) / 12), iL,
            (xc, iT + hT * (12 - xc) / 12)]
    tf = lambda pts: [(round(TILE / 2 + (x - 12) * u, 1), round(KITE_TOP + y * u, 1)) for x, y in pts]
    L = tf(left)
    R = [(round(TILE - x, 1), y) for x, y in L][::-1]
    top = (16.0, round(KITE_TOP + (PANEL_Y - PANEL * hT) * u, 1))
    side = round(PANEL * 12 * u, 1)
    axis = round(KITE_TOP + PANEL_Y * u, 1)
    core = [top, (round(16 + side, 1), axis), (16.0, round(KITE_TOP + (PANEL_Y + PANEL * hB) * u, 1)), (round(16 - side, 1), axis)]
    return dict(left=L, right=R, core=core, u=u)


def tile_d(n=TILE, r=TILE_RX):
    return (f'M{r} 0H{n - r}A{r} {r} 0 0 1 {n} {r}V{n - r}A{r} {r} 0 0 1 {n - r} {n}H{r}A{r} {r} 0 0 1 0 {n - r}'
            f'V{r}A{r} {r} 0 0 1 {r} 0Z')


# ---------------------------------------------------------------- pixel-run helpers (frame sources)
def runs(px, key):
    """horizontal runs of `key` -> [(x, y, w)]"""
    out = []
    for y, row in enumerate(px):
        x = 0
        while x < len(row):
            if row[x] == key:
                x0 = x
                while x < len(row) and row[x] == key:
                    x += 1
                out.append((x0, y, x - x0))
            else:
                x += 1
    return out


def runs_d(px, key):
    return ''.join(f'M{x} {y}h{w}v1h-{w}Z' for x, y, w in runs(px, key))


def ascii(px):
    return '\n'.join(f'{y:2d} ' + ''.join(row) for y, row in enumerate(px))
